### ISSUE TITLE
Gateway: Skill Repositories Verwalten (CRUD)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/Search-AI-Facade-service#1]
In `Search-AI-Facade-service` prüfen, dass die folgenden Funktionen des `nm-skill-services` erreichbar sind:
- **POST** skill-repositories/ für das Anlegen eines SkillRepositories. 
  - [x] Implementiert
  - [ ] Abhängigkeiten geprüft
  - [ ] Integrationstests

- **GET** skill-repositories/byOwner/{ownerId} für die Abfrage aller Skill Repositories. Der Owner ist eine vom Client bestimmbare Id, die ich beim POST angelegt habe. 
  - [x] Implementiert
  - [ ] Abhängigkeiten geprüft
  - [ ] Integrationstests

- **GET** skill-repositories/byId/{repositoryId} für die Abfrage eines SkillRepositories basierend auf der SkillRepository Id von euch
  - [x] Implementiert
  - [ ] Abhängigkeiten geprüft
  - [ ] Integrationstests

- **DELETE** skill-repositories/{repoId}/del für das Löschen eines Skill-Repositories. Ist Äquivalent mit der Löschung aller Skills aus einem Repository. Mit Außnahme, dass nichts gelöscht wird, sofern eine Löschung innerhalb der Kette nicht durchgeführt werden kann. Werden alle SkillsRepos eines Owners gelöscht, kann der Owner mitgelöscht werden, sofern ihr den dann noch irgendwo trackt. 
  - [x] Implementiert
  - [ ] Abhängigkeiten geprüft
  - [ ] Integrationstests

- **PUT** skill-repositories/ sollte es auch geben. 
  - [x] Implementiert
  - [ ] Abhängigkeiten geprüft
  - [ ] Integrationstests

### Jeweils pro Endpoint:
- Implementierung im Gateway
- Prüfen ob weitere Services von L3S berrührt werden
- Integrationstests: Entweder Aufruf auf Staging oder idealerweise Test-Docker-Container hochfahren

**Comment by WenzelSSE** [comment]
Post und Put gegen den selben Endpoint nicht möglich - PUT skill-repositories/ für Adaption  und POST skill-repositories/ für das Anlegen eines SkillRepositories. 

Würde für  das Anlegen eines SkillRepositories  skill-repositories/create/  als Endpoint verwenden wollen

**Comment by WenzelSSE** [comment]
Integrationstests: Entweder Aufruf auf Staging oder idealerweise Test-Docker-Container hochfahren ->
wie von dir vorgeschlagen und bereits abgestimmt gehe ich da gegen Staging

**Comment by WenzelSSE** [comment]
Prüfen ob weitere Services von L3S berrührt werden - wie soll dies geschehen?

**Comment by WenzelSSE** [comment]
Von Sascha via Skype: 
Das ist die generelle Frage nach dem Sinn des Gateways: Zumindest aus SSE-Sicht macht es nur dann Sinn, wenn es Aufrufe gibt, die mehr als einen der gekapselten Dienste beeinflussen. Andernfalls ist es nur unnötiger Entwicklungsaufwand und Performance-Overhead.
Dazu muss man nun mit den L3S-Leuten und der Nachwuchsstiftung prüfen ob z.B. die L3S-Services darauf reagieren sollen, wenn ein neuer Skill angelegt wird. Idealerweise müsste man das nur mit den L3S-Leuten absprechen, bis sie aber eine Idee davon haben was das mit den Skills soll, muss man es wohl eher in der größeren Runde besprechen. Also z.B. Montags oder einen Donnerstagstermin mit Eugen und Florian und mit denen klären was z.B. L3S-Search indizieren soll. Da hatte Eugen beim letzten Meeting schon die Skills erwähnt.

**Comment by WenzelSSE** [comment]
Terminfindung angestoßen

**Comment by WenzelSSE** [comment]
canceled
