### ISSUE TITLE
Gateway: Skills Verwalten (CRUD)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/Search-AI-Facade-service#2]
In `Search-AI-Facade-service` prüfen, dass die folgenden Funktionen des `nm-skill-services` erreichbar sind:
- **GET** skill/{skillId} für die Abfrage an einen Skill basierend auf der Skill-Id von euch, hierbei sollen sowohl parents wie auch children (nestedSkills) des Skills angegeben werden. 
  - [ ] Implementiert
  - [ ] Abhängigkeiten geprüft
  - [ ] Integrationstests
 
- **POST** skill/ zum Anlegen eines neuen Skills mit Kinder (nestedSkills), welche angegeben werden durch ein Array aus Ids der Skills, die Kinder sein sollen. 
  - [ ] Implementiert
  - [ ] Abhängigkeiten geprüft
  - [ ] Integrationstests
 
- **DELETE** skill/{skillId}/del für das Löschen eines Skills. Sollte nicht erlaubt werden, wenn der Skill bereits irgendwo anders verwendet wird. Sollte aber erlaubt sein, wenn der Skill Kinder hat. In diesem Fall sollen auch alle Kinder mitgelöscht werden, sofern erlaubt. Ist irgendwas in der Kette der Löschungen nicht erlaubt, soll nichts gelöscht werden (Atomarität jeder Transaktion bewahren) und es soll ein 400er-Fehler geworfen werden.
  - [ ] Implementiert
  - [ ] Abhängigkeiten geprüft
  - [ ] Integrationstests
 
- **PUT** skill/{skillId}/adapt . Es soll die Möglichkeit geben Skills zu modifizieren. Hier sind erstmal keine Versionen notwendig, denn das soll auch hier erstmal nur erlaubt sein, wenn der Skill nirgends verwendet wird. (In dem Fall würdet ihr ja auch keine neue Version anlegen wollen, oder?). Dabei kann ich die Kinder des Skills festlegen durch Angabe der nestedSkills. Dabei werden Ids der Skills angegeben. Existieren die Skills nicht oder würde die Eltern-Kind-Beziehung zu einem Zyklus führen, schlägt die Transaktion fehl (mit 400er antworten) und es soll nichts verändert werden (Atomarität jeder Transaktion bewahren). 
  - [ ] Implementiert
  - [ ] Abhängigkeiten geprüft
  - [ ] Integrationstests
 

### Jeweils pro Endpoint:
- Implementierung im Gateway
- Prüfen ob weitere Services von L3S berrührt werden
- Integrationstests: Entweder Aufruf auf Staging oder idealerweise Test-Docker-Container hochfahren

**Comment by WenzelSSE** [comment]
gecancelt

**Comment by WenzelSSE** [comment]
gecancelt
